/**
 * Offline replay of the source workbooks.
 *
 * This exists so the query engine and agent can be tested deterministically
 * without a monday.com account. It is NOT a shortcut around the assignment's
 * "query monday.com dynamically" requirement:
 *
 *   • It only activates when DATA_SOURCE=mock is set explicitly.
 *   • The dataset file it reads is generated by `npm run mock:build` from the
 *     original .xlsx files and is gitignored — no spreadsheet data is
 *     committed to the repository or shipped in the build.
 *   • It hands back rows in the same shape monday.com's API produces, so every
 *     layer above it runs unmodified.
 */

import { readFile } from 'node:fs/promises';
import path from 'node:path';
import type { RawRow } from '../data/records.ts';

type MockFile = {
  generatedAt: string;
  boards: Record<string, { name: string; rows: RawRow[] }>;
};

let loaded: MockFile | null = null;

async function load(): Promise<MockFile> {
  if (loaded) return loaded;
  const file = path.join(process.cwd(), 'data', 'mock-dataset.json');
  try {
    loaded = JSON.parse(await readFile(file, 'utf8')) as MockFile;
    return loaded;
  } catch {
    throw new Error(
      `DATA_SOURCE=mock but data/mock-dataset.json is missing. Generate it with:\n` +
      `  npm run mock:build -- "<path to Deal funnel Data.xlsx>" "<path to Work_Order_Tracker Data.xlsx>"`,
    );
  }
}

export async function loadMockRows(boardId: string): Promise<RawRow[]> {
  const f = await load();
  return f.boards[boardId]?.rows ?? [];
}

export async function mockBoardMeta() {
  const f = await load();
  return Object.entries(f.boards).map(([id, b]) => ({
    id, name: b.name, boardId: `mock-${id}`, items: b.rows.length,
  }));
}
